# Generated by Django 4.0.6 on 2022-07-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_bonus_alter_product_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('w', 'white'), ('b', 'black'), ('r', 'red')], default='w', max_length=10),
        ),
    ]
