# Generated by Django 4.0.6 on 2022-07-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='int',
            field=models.CharField(choices=[(0, 'white'), (1, 'black'), (2, 'red')], default=0, max_length=10),
        ),
    ]
