# Generated by Django 4.0.6 on 2022-07-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='max length - 255', max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
