# Generated by Django 4.0.6 on 2022-07-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='int',
            field=models.IntegerField(choices=[(0, 'white'), (1, 'black'), (2, 'red')], default=0),
        ),
    ]
