# Generated by Django 4.0.6 on 2022-07-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tag_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='tag',
        ),
    ]
