# Generated by Django 4.0.6 on 2022-07-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_product_color_remove_product_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
    ]
